- name: Print linux distribution and version
  hosts: all
  tasks:
    - name: Get OS info 10.0.3.8
      command: cat /etc/system-release
      register: login
    - debug: msg="{{ login.stdout }}"
    - set_fact:
        companyname: "{{ login.stdout }}"
        companyname: "{{ login.stdout }}"